/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    HabitChain: {
      address: "0xf3390f611bf36ca72a416211f033947129a485e2",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_aavePool",
              type: "address",
              internalType: "address",
            },
            {
              name: "_weth",
              type: "address",
              internalType: "address",
            },
            {
              name: "_aWeth",
              type: "address",
              internalType: "address",
            },
            {
              name: "_treasury",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "MIN_STAKE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ONE_DAY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "aWeth",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IAToken",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "aavePool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IPool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "checkIn",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createHabit",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "stakeAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "forceSettle",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getHabit",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct HabitChain.Habit",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "user",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "stakeAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "aTokenAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "liquidityIndex",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "lastCheckIn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "checkInCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isSettled",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getHabitCurrentValue",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "currentValue",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "yieldEarned",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTreasuryBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserActiveHabitsCount",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserBalance",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserHabits",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "globalSettle",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "habits",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "stakeAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "aTokenAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "liquidityIndex",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "createdAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastCheckIn",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "checkInCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isSettled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextHabitId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "treasury",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "treasuryBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userBalances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userHabits",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "weth",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IWETH",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawTreasury",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CheckInCompleted",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "checkInCount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GlobalSettlementCompleted",
          inputs: [
            {
              name: "totalSettled",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "successfulHabits",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "failedHabits",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HabitCreated",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "stakeAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HabitSettled",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "success",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "totalAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "yieldEarned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TreasuryFunded",
          inputs: [
            {
              name: "habitId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyCheckedInToday",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyHabitName",
          inputs: [],
        },
        {
          type: "error",
          name: "HabitAlreadySettled",
          inputs: [],
        },
        {
          type: "error",
          name: "HabitNotActive",
          inputs: [],
        },
        {
          type: "error",
          name: "HabitNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientStake",
          inputs: [],
        },
        {
          type: "error",
          name: "NotHabitOwner",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 37106108,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
